import { StyleSheet, Platform } from 'react-native';

const accent = '#1989a8';
const accentDark = '#05647e';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9f9f9',
  },
  header: {
    backgroundColor: '#1989a8',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingTop: Platform.OS === 'ios' ? 54 : 14,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
 backButton: {
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '400',
    color: '#ffffff',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
  },
  headerNotificationButton: {
    width: 40,
    height: 40,
    alignItems: 'flex-end',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    right: 2,
    top: 8,
    width: 10,
    height: 10,
    borderRadius: 9999,
    backgroundColor: '#ef4444',
    borderWidth: 2,
    borderColor: accent,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 24,
  },
  dateRangeSelector: {
    backgroundColor: '#ffffff',
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  dateRangeText: {
    flex: 1,
    marginHorizontal: 12,
    color: '#1f2937',
    fontSize: 17,
    fontWeight: '500',
  },
  listContainer: {
    marginTop: 24,
    gap: 20,
  },
  eventCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    borderLeftWidth: 4,
    borderLeftColor: accentDark,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 30,
    elevation: 3,
    overflow: 'hidden',
  },
  eventCardInner: {
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 16,
    gap: 16,
  },
  eventHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  eventTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  eventId: {
    color: accentDark,
    fontSize: 16,
    fontWeight: '800',
  },
  titleDivider: {
    width: 5,
    height: 5,
    borderRadius: 9999,
    backgroundColor: '#9ca3af',
    marginHorizontal: 8,
  },
  eventTitle: {
    flexShrink: 1,
    color: '#1f2937',
    fontSize: 16,
    fontWeight: '500',
  },
  dateBadge: {
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#dff1ff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dateBadgeText: {
    color: accentDark,
    fontSize: 13,
    fontWeight: '700',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metaText: {
    color: '#4b5563',
    fontSize: 14,
    fontWeight: '500',
  },
  metaDivider: {
    width: 1,
    height: 34,
    backgroundColor: '#d1d5db',
    marginHorizontal: 12,
  },
  eventPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#f0f9ff',
    borderWidth: 1,
    borderColor: '#bae6fd',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexWrap: 'wrap',
  },
  eventPillIconWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventPillText: {
    color: '#1f2937',
    fontSize: 15,
    fontWeight: '700',
  },
  levelChip: {
    backgroundColor: accent,
    borderRadius: 9999,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginLeft: 115,

  },
  levelChipText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  participantBlock: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexShrink: 1,
  },
  avatarStack: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarWrap: {
    width: 40,
    height: 40,
    borderRadius: 9999,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#ffffff',
    backgroundColor: '#e5e7eb',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  emptyAvatar: {
    width: 40,
    height: 40,
    borderRadius: 9999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  participantTextWrap: {
    minWidth: 58,
  },
  participantCount: {
    color: '#1f2937',
    fontSize: 17,
    fontWeight: '800',
  },
  participantLabel: {
    marginTop: 2,
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  priceAndActionBlock: {
    flexShrink: 0,
    alignItems: 'flex-end',
    gap: 10,
  },
  priceText: {
    color: accentDark,
    fontSize: 18,
    fontWeight: '800',
  },
  priceSuffix: {
    color: '#6b7280',
    fontSize: 14,
    fontWeight: '500',
  },
  detailButton: {
    minWidth: 146,
    minHeight: 44,
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  detailButtonJoined: {
    backgroundColor: '#0f766e',
  },
  detailButtonFull: {
    backgroundColor: '#94a3b8',
  },
  detailButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  emptyState: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingVertical: 28,
    paddingHorizontal: 20,
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 2,
  },
  emptyStateTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '700',
  },
  emptyStateText: {
    color: '#6b7280',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  noteBox: {
    marginTop: 24,
    paddingVertical: 16,
    paddingHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  noteText: {
    flex: 1,
    color: accent,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  rangePickerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  rangePickerSheet: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 18,
    gap: 12,
  },
  rangePickerTitle: {
    color: '#0f172a',
    fontSize: 17,
    fontWeight: '800',
  },
  rangePickerOption: {
    minHeight: 50,
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: '#f8fafc',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  rangePickerOptionActive: {
    backgroundColor: 'rgba(25, 137, 168, 0.1)',
    borderColor: 'rgba(25, 137, 168, 0.22)',
  },
  rangePickerOptionText: {
    flex: 1,
    color: '#334155',
    fontSize: 14,
    fontWeight: '600',
  },
  rangePickerOptionTextActive: {
    color: accent,
  },
  bottomNavBar: {
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 28 : 10,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
  bottomNavItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 2,
  },
  bottomNavItemActive: {
  },
  bottomNavLabel: {
    color: '#717a6d',
    fontSize: 11,
    fontWeight: '600',
  },
  bottomNavLabelActive: {
    color: accent,
  },
});

export default styles;