import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9f9f9',
  },
  header: {
    backgroundColor: '#1989a8',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingTop: Platform.OS === 'ios' ? 54 : 14,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  backButton: {
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '400',
    color: '#ffffff',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
  },
  scrollContent: {
    paddingBottom: 32,
  },
  heroSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    padding: 16,
    backgroundColor: '#ffffff',
  },
  heroImage: {
    width: 112,
    height: 112,
    borderRadius: 8,
    backgroundColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  heroInfo: {
    flex: 1,
    gap: 4,
  },
  venueName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    lineHeight: 25,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  reviewCount: {
    fontSize: 12,
    color: '#6b7280',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
    paddingTop: 4,
  },
  locationText: {
    flex: 1,
    fontSize: 14,
    color: '#414962',
    lineHeight: 20,
  },
  sportRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  sportText: {
    fontSize: 14,
    color: '#4b5563',
    lineHeight: 20,
  },
  dateRangePicker: {
    marginHorizontal: 16,
    marginTop: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateRangeLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  dateRangeText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#111827',
  },
  contentTabs: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    marginTop: 16,
    backgroundColor: '#ffffff',
  },
  contentTab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  contentTabActive: {
    borderBottomColor: '#1989a8',
  },
  contentTabText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#6b7280',
  },
  contentTabTextActive: {
    color: '#1989a8',
  },
  priceSection: {
    padding: 16,
    gap: 12,
  },
  priceSectionAlt: {
    backgroundColor: '#f9fafb',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#166534',
  },
  dayToggleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    paddingTop: 4,
  },
  dayToggle: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    alignItems: 'center',
  },
  dayToggleActive: {
    backgroundColor: '#258fb0',
    borderColor: '#258fb0',
  },
  dayToggleText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6b7280',
  },
  dayToggleTextActive: {
    color: '#ffffff',
    fontWeight: '600',
  },
  tableCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f3f4f6',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#f9fafb',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  tableHeaderCell: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tableHeaderCellWide: {
    flex: 1.4,
  },
  tableHeaderText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4b5563',
    textAlign: 'center',
    lineHeight: 16,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f9fafb',
  },
  tableRowLast: {
    borderBottomWidth: 0,
  },
  tableCell: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tableCellWide: {
    flex: 1.4,
  },
  timeSlotText: {
    fontSize: 12,
    color: '#1f2937',
    textAlign: 'center',
  },
  fixedPriceText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#16a34a',
    textAlign: 'center',
  },
  walkInPriceText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#258fb0',
    textAlign: 'center',
  },
  priceNoteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  priceNoteText: {
    flex: 1,
    fontSize: 10,
    color: '#6b7280',
    lineHeight: 15,
  },
  regulationsSection: {
    paddingHorizontal: 16,
    paddingTop: 32,
    paddingBottom: 16,
    gap: 32,
    backgroundColor: '#ffffff',
  },
  regulationCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bec8ce',
    padding: 16,
    gap: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  regulationCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  regulationCardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#00647e',
    lineHeight: 28,
  },
  ruleList: {
    gap: 12,
  },
  ruleItemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  ruleItemText: {
    flex: 1,
    fontSize: 16,
    color: '#1a1c1c',
    lineHeight: 24,
  },
  policyList: {
    gap: 16,
  },
  policyRow: {
    backgroundColor: '#f3f3f4',
    borderRadius: 8,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  policyLabel: {
    fontSize: 16,
    color: '#1a1c1c',
    lineHeight: 24,
  },
  policyValueTeal: {
    fontSize: 16,
    color: '#00647e',
    lineHeight: 24,
  },
  policyValueOrange: {
    fontSize: 16,
    color: '#884e00',
    lineHeight: 24,
  },
  policyValueRed: {
    fontSize: 16,
    color: '#ba1a1a',
    lineHeight: 24,
  },
  refundNote: {
    fontSize: 12,
    color: '#3e484d',
    lineHeight: 16,
    fontStyle: 'italic',
    paddingHorizontal: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  modalContent: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    gap: 8,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  modalOption: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 12,
    gap: 2,
  },
  modalOptionActive: {
    borderColor: '#1989a8',
    backgroundColor: '#f0f9fb',
  },
  modalOptionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  modalOptionLabelActive: {
    color: '#1989a8',
  },
  modalOptionSubLabel: {
    fontSize: 12,
    color: '#6b7280',
  },
});

export default styles;
