import { StyleSheet, Platform, StatusBar } from 'react-native';

const TEAL = '#1989a8';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9f9f9',
  },
  header: {
    backgroundColor: TEAL,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingTop: Platform.OS === 'ios' ? 54 : 14 + (StatusBar.currentHeight || 0),
    gap: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#ffffff',
  },
  scrollContent: {
    paddingBottom: 36,
  },
  venueCard: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  venueImage: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: '#e5e7eb',
  },
  venueInfo: {
    flex: 1,
    gap: 4,
  },
  venueName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1f2937',
  },
  venueAddressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  venueAddress: {
    fontSize: 13,
    color: '#6b7280',
    flex: 1,
  },
  ratingOverviewCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    margin: 16,
    padding: 16,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
    alignItems: 'center',
  },
  ratingLeft: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1.1,
    borderRightWidth: 1,
    borderRightColor: '#f3f4f6',
    paddingRight: 12,
  },
  ratingScore: {
    fontSize: 36,
    fontWeight: '800',
    color: '#1f2937',
  },
  starsRow: {
    flexDirection: 'row',
    gap: 2,
    marginVertical: 4,
  },
  ratingCountText: {
    fontSize: 12,
    color: '#9ca3af',
  },
  ratingRight: {
    flex: 1.5,
    paddingLeft: 16,
    gap: 6,
  },
  progressBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  barLabel: {
    fontSize: 12,
    color: '#4b5563',
    fontWeight: '600',
    width: 10,
    textAlign: 'center',
  },
  barTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#f3f4f6',
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: '#f97316',
  },
  barCount: {
    fontSize: 11,
    color: '#9ca3af',
    width: 22,
    textAlign: 'right',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 8,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1f2937',
  },
  seeAllText: {
    fontSize: 13,
    color: '#1989a8',
    fontWeight: '600',
  },
  categoriesContainer: {
    paddingLeft: 16,
    paddingRight: 8,
    marginBottom: 20,
  },
  categoryBox: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    marginRight: 10,
    width: 76,
    borderWidth: 1,
    borderColor: '#f3f4f6',
    gap: 6,
  },
  categoryLabel: {
    fontSize: 10,
    color: '#6b7280',
    textAlign: 'center',
  },
  categoryScore: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1f2937',
  },
  reviewsList: {
    paddingHorizontal: 16,
    gap: 16,
  },
  reviewCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 1,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  reviewerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  reviewerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#e5e7eb',
  },
  reviewerName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1f2937',
  },
  reviewMeta: {
    alignItems: 'flex-end',
    gap: 2,
  },
  reviewDate: {
    fontSize: 11,
    color: '#9ca3af',
  },
  reviewComment: {
    fontSize: 13,
    lineHeight: 18,
    color: '#4b5563',
    marginBottom: 12,
  },
  photoRow: {
    flexDirection: 'row',
    gap: 8,
  },
  reviewPhoto: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 8,
    backgroundColor: '#f3f4f6',
  },
  writeReviewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: TEAL,
    borderRadius: 12,
    height: 48,
    marginHorizontal: 16,
    marginTop: 24,
    gap: 8,
    backgroundColor: '#ffffff',
  },
  writeReviewText: {
    fontSize: 15,
    fontWeight: '600',
    color: TEAL,
  },
});

export default styles;
