import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9f9f9',
  },
  header: {
    backgroundColor: '#1989a8',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingTop: Platform.OS === 'ios' ? 54 : 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
    zIndex: 10,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoIcon: {
    width: 22,
    height: 35,
  },
  logoText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#ffffff',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  topIconButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 36,
    gap: 22,
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  avatarWrap: {
    position: 'relative',
  },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 4,
    borderColor: '#ffffff',
    backgroundColor: '#e5e7eb',
  },
  cameraButton: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#1989a8',
    borderWidth: 2,
    borderColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInfo: {
    flex: 1,
    paddingTop: 10,
    gap: 18,
  },
  fullName: {
    fontSize: 30,
    fontWeight: '700',
    color: '#1f2937',
  },
  editButton: {
    alignSelf: 'flex-start',
    borderWidth: 1.5,
    borderColor: '#1989a8',
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  editButtonText: {
    color: '#1989a8',
    fontSize: 16,
    fontWeight: '700',
  },
  membershipCard: {
    minHeight: 262,
    borderRadius: 20,
    overflow: 'hidden',
    padding: 20,
  },
  membershipBackground: {
    borderRadius: 20,
  },
  membershipOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#00647e',
    opacity: 0.96,
  },
  membershipContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 18,
    zIndex: 1,
  },
  membershipLeft: {
    flex: 1,
    gap: 12,
  },
  sectionEyebrow: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  membershipTitle: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '700',
    lineHeight: 32,
  },
  progressBarTrack: {
    width: '100%',
    height: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.25)',
    overflow: 'hidden',
    marginTop: 6,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#ffffff',
  },
  progressText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '400',
  },
  membershipDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.35)',
    marginVertical: 14,
  },
  pointsWrap: {
    minWidth: 110,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  starBadge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pointsLabel: {
    color: '#ffffff',
    fontSize: 14,
    opacity: 0.85,
  },
  pointsValue: {
    color: '#ffffff',
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 36,
  },
  pointsUnit: {
    fontSize: 14,
    fontWeight: '400',
    opacity: 0.85,
  },
  bookingCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 2,
    gap: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1f2937',
  },
  seeAllText: {
    color: '#1989a8',
    fontSize: 16,
    fontWeight: '700',
  },
  bookingStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  bookingStatItem: {
    width: '18%',
    minWidth: 58,
    alignItems: 'center',
    gap: 8,
  },
  bookingStatIconBox: {
    width: 72,
    height: 72,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingStatLabel: {
    textAlign: 'center',
    color: '#4b5563',
    fontSize: 12,
    lineHeight: 16,
  },
  bookingStatCount: {
    textAlign: 'center',
    color: '#1f2937',
    fontSize: 18,
    fontWeight: '700',
  },
  menuCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 2,
  },
  menuRow: {
    paddingHorizontal: 16,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuRowDivider: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(190, 200, 206, 0.3)',
  },
  menuLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  menuTitle: {
    fontSize: 16,
    color: '#1f2937',
  },
  logoutButton: {
    backgroundColor: '#ef4444',
    borderRadius: 16,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    shadowColor: '#ef4444',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 3,
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
});

export default styles;
